name: Dev Builds
on: 
  push:
    branches:
      - "main"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      - run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          generate_release_notes: true
          prerelease: true
          